{{- if .Values.licenseSource.enabled }}
{{- if not .Values.licenseSource.sourceRef }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: license
  namespace: {{ .Release.Namespace }}
spec:
  interval: 10s
  url: {{ .Values.licenseSource.url }}
  {{- if or .Values.licenseSource.tag .Values.licenseSource.branch }}
  ref:
    {{- if .Values.licenseSource.tag }}
    tag: {{ .Values.licenseSource.tag }}
    {{- end }}
    {{- if .Values.licenseSource.branch }}
    branch: {{ .Values.licenseSource.branch }}
    {{- end }}
  {{- end }}
  {{- if .Values.licenseSource.secretRef }}
  secretRef:
    name: {{ .Values.licenseSource.secretRef }}
  {{- end }}
{{- end }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: license
  namespace: {{ .Release.Namespace }}
spec:
  interval: 10m0s
  {{- if not .Values.licenseSource.sourceRef }}
  sourceRef:
    kind: GitRepository
    name: license
    namespace: {{ .Release.Namespace }}
  {{- else }}
  sourceRef:
{{- toYaml .Values.licenseSource.sourceRef | nindent 4 }}
  {{- end }}
  path: {{ .Values.licenseSource.path }}
  prune: true
{{- end }}
