# Flamingo 
nameOverride: ""
fullnameOverride: ""

service:
  port: 443

ingress:
  enabled: true
  # className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  hosts:
    - paths:
        - path: /?(.*)
          pathType: ImplementationSpecific