# Flamingo 
nameOverride: ""
fullnameOverride: ""

service:
  port: 443


ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  hosts:
    - host: flamingo.demo3.weavegitops.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: argo-tls
     hosts:
       - flamingo.demo3.weavegitops.com
