keycloak:
  metrics:
    enabled: true
  service:
    # place cloud provider load balancer annotations below
    # Example:
    #   annotations:
    #     service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    annotations: {}
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: auth.solo-weaveworks-webinar.trial.cx.weave.works
    tls: enabled