keycloak:
  metrics:
    enabled: true
  service:
    # place cloud provider load balancer annotations below
    # Example:
    #   annotations:
    #     service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    annotations: {}
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    enabled: true
    ingressClassName: nginx
    hostname: auth.solo-weaveworks-webinar.trial.cx.weave.works
    tls: true
  extraStartupArgs: |
    -Dkeycloak.frontendUrl=https://auth.solo-weaveworks-webinar.trial.cx.weave.works
  extraEnvVars:
    - name: KEYCLOAK_LOG_LEVEL
      value: DEBUG
    - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KC_HOSTNAME_STRICT_HTTPS
      value: "false"
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KC_PROXY
      value: "edge"
    - name: KC_HOSTNAME_STRICT
      value: "false"
    - name: KC_HOSTNAME_URL
      value: "https://auth.solo-weaveworks-webinar.trial.cx.weave.works"
    - name: KC_HOSTNAME_ADMIN_URL
      value: "https://auth.solo-weaveworks-webinar.trial.cx.weave.works"