apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.clusterIssuerEmail }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          route53:
            region: {{ .Values.region }}
            accessKeyID: {{ .Values.accessKeyId }}
            secretAccessKeySecretRef:
              name: {{ .Values.externalSecret.secretName }}
              key: secret-access-key
