apiVersion: v2
name: tekton-automation
description: A Weaveworks Helm chart for a Cloudnative Buildpacks and Tekton Automation Framework
type: application
version: 0.0.8
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://weave.works

keywords:
- tekton
- tekton-pipelines
- cicd

maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": tekton-automation
  "weave.works/category": CICD
  "weave.works/operator": "true"
  "weave.works/layer": layer-2
  "weave.works/links": |
    - name: Chart Sources
      url: https://weave.works
    - name: Upstream Project
      url: https://github.com/tektoncd/
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"
