{{- if .Values.externalSecret.create }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: external-dns-static-secret
  namespace: 
spec:
  data:
  - remoteRef:
      key: {{ .Values.secretManager.path }}
      property: {{ .Values.secretKey }}
    secretKey: {{ .Values.secretKey }}
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.clusterSecretStore.name }}
  target:
    creationPolicy: Owner
    name: {{ .Values.secretName }}
status:
  refreshTime: null
{{- end }}
