apiVersion: v1
kind: Secret
metadata:
  name: 'ci-template-registry-secret'
  namespace: tekton-pipelines
  annotations:
    tekton.dev/docker-0: {{ .Values.registry }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.dockerHubUsername }}
  password: {{ .Values.accessToken }}
