---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: flux-snyk-eventlistener
  namespace: tekton-pipelines
spec:
  serviceAccountName: snyk-triggers-sa
  triggers:
    - name: flux-snyk-triggerbinding
      bindings:
        - ref: flux-snyk-triggerbinding
      template:
        ref: flux-snyk-triggertemplate