apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: snyk-scan
  namespace: tekton-pipelines
spec:
  params:
    - name: repository
      type: string
    - name: revision
      type: string
    - name: namespace
      type: string
  workspaces:
    - name: snyk-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: snyk-clone
      workspaces:
        - name: output
          workspace: snyk-workspace
      params:
        - name: repository
          value: "$(params.repository)"
        - name: revision
          value: "$(params.revision)"
        - name: namespace
          value: "$(params.namespace)"
    - name: snyk-scan
      runAfter:
        - fetch-repository
      taskRef:
        name: snyk-scan
      workspaces:
        - name: source
          workspace: snyk-workspace
      params:
        - name: snyk-token
          value: "{{ .Values.snykToken }}"
        - name: target-directory
          value: "{{ .Values.targetDirectory }}"
