# CONFIRMED: Provider is targeted by Alert and sends generic notification to eventlistener
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: snyk-provider
  namespace: flux-system
spec:
  type: generic
  address: http://el-flux-snyk-eventlistener.tekton-pipelines.svc.cluster.local:8080